app = "futuros-lucas"

[build]

[env]
  TZ = "America/Sao_Paulo"

[experimental]
  auto_stop_machines = false
  auto_start_machines = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256